[Subject]
id = Name_Round

[Experiment]
name = Aphantasia_Mental_Rotation
# 想要运行的总轮数 (设置为 0 则运行 stimuli 文件夹内所有的图片)
num_trials = 30
# 刺激物呈现的最长等待时间
max_wait_sec = 20.0
# 注视点呈现时间
fixation_duration = 0.5

[Keys]
same = f
different = j
escape = escape
strategy_intuition = f
strategy_logic = j

[Paths]
stimuli_dir = stimuli
data_dir = data/raw